# -*- coding: utf-8 -*-
"""iris_app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opCSlQi0uDcoVhIFJdtVn1a580plmZmp
"""

!pip install streamlit
import streamlit as st
import pickle
import numpy as np

# Load model
model = pickle.load(open('iris_model.pkl', 'rb'))

st.title("🌸 Iris Flower Prediction App")
st.write("Predict the species of Iris flower using machine learning.")

# Input fields
sepal_length = st.slider("Sepal Length (cm)", 4.0, 8.0, 5.1)
sepal_width = st.slider("Sepal Width (cm)", 2.0, 4.5, 3.5)
petal_length = st.slider("Petal Length (cm)", 1.0, 7.0, 1.4)
petal_width = st.slider("Petal Width (cm)", 0.1, 2.5, 0.2)

# Predict button
if st.button("Predict"):
    features = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    prediction = model.predict(features)
    species = ['Setosa', 'Versicolor', 'Virginica']
    st.success(f"The predicted Iris species is: 🌼 **{species[prediction[0]]}**")